sudo: required
services:
- docker
language: python
python:
- '3.6'
install:
- sudo apt-get install -y golang-go
- pip install -U yadage
script:
- docker ps
- go get sigs.k8s.io/kind
- kind create cluster
