sudo: required
services:
- docker
language: python
python:
- '3.6'
install:
- sudo apt-get install golang-1.10-go
#- pip install -U yadage
script:
- docker ps
- /usr/lib/go-1.10/bin/go version
- /usr/lib/go-1.10/bin/go get sigs.k8s.io/kind
- kind create cluster
